# Generated by Django 4.1.5 on 2023-04-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AirplaneModel",
            fields=[
                (
                    "icao24",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("registration", models.CharField(max_length=20)),
                ("manufacturername", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("serialnumber", models.CharField(max_length=50)),
                ("operator", models.CharField(max_length=50)),
                ("owner", models.CharField(max_length=50)),
                ("categoryDescription", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "airplanes_db",
            },
        ),
    ]
