# Generated by Django 4.1.5 on 2023-04-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="aircraftModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icao24", models.CharField(max_length=10)),
                ("registration", models.CharField(max_length=20)),
                ("manufacturername", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("serialnumber", models.CharField(max_length=50)),
                ("operator", models.CharField(max_length=50)),
                ("owner", models.CharField(max_length=50)),
                ("categoryDescription", models.CharField(max_length=50)),
            ],
        ),
    ]
