# Generated by Django 4.1.5 on 2023-05-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FavoritesListModel",
            fields=[
                (
                    "icao24",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("record_type", models.CharField(max_length=20)),
                ("user_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "favorites_db",
            },
        ),
    ]
