# Generated by Django 4.1.5 on 2023-04-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DestinationsModel",
            fields=[
                (
                    "callsign",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("origin", models.CharField(max_length=15)),
                ("destination", models.CharField(max_length=15)),
            ],
            options={
                "db_table": "destinations_db",
            },
        ),
    ]
