# Generated by Django 4.1.5 on 2023-04-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircrafts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("_id", models.IntegerField()),
                ("ident", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("latitude_deg", models.FloatField()),
                ("longitude_deg", models.FloatField()),
                ("elevation_ft", models.FloatField()),
                ("continent", models.CharField(blank=True, max_length=50)),
                ("iso_country", models.CharField(blank=True, max_length=50)),
                ("iso_region", models.CharField(blank=True, max_length=50)),
                ("municipality", models.CharField(blank=True, max_length=50)),
                ("scheduled_service", models.BooleanField(blank=True)),
                ("gps_code", models.CharField(max_length=50)),
                ("iata_code", models.CharField(blank=True, max_length=50)),
                ("local_code", models.CharField(blank=True, max_length=50)),
                ("home_link", models.CharField(blank=True, max_length=200)),
                ("wikipedia_link", models.CharField(blank=True, max_length=200)),
                ("keywords", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
