# Generated by Django 4.1.5 on 2023-04-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aircrafts",
            name="scheduled_service",
            field=models.CharField(max_length=50),
        ),
    ]
