# Generated by Django 4.1.5 on 2023-04-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airports", "0002_alter_aircrafts_scheduled_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aircrafts",
            name="scheduled_service",
            field=models.BooleanField(),
        ),
    ]
