# Generated by Django 4.1.5 on 2023-04-02 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airports", "0003_alter_aircrafts_scheduled_service"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Aircrafts",
            new_name="Airports",
        ),
    ]
